[package]
name = "tc-slint"
version.workspace = true
edition.workspace = true
description = "Tangential Cold (slint frontend)"
build = "build.rs"

[[bin]]
name = "tc-slint"
path = "src/main.rs"

[dependencies]
tc-core.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
hostname.workspace = true
slint = { version = "~1.17", features = ["unstable-fontique-010"] }

[build-dependencies]
slint-build = "1.17"
